name: "❔ Add a Problem"
description: "Add a LeetCode problem."
title: "[PROBLEM] 0. Problem Title"
labels: ["hacktoberfest", "problem"]
body:
  - type: dropdown
    id: problem-difficulty
    attributes:
      label: Difficulty
      description: "The difficulty of the problem."
      options:
        - "![EASY](https://img.shields.io/badge/-EASY-40c040?style=for-the-badge&logo=LeetCode&logoColor=white)"
        - "![MEDIUM](https://img.shields.io/badge/-MEDIUM-ffa116?style=for-the-badge&logo=LeetCode&logoColor=white)"
        - "![Hard](https://img.shields.io/badge/-Hard-FF4040?style=for-the-badge&logo=LeetCode&logoColor=black)"
    validations:
      required: true
      
  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: "The description of the problem."
      placeholder: "You are given..."
    validations:
      required: true

  - type: input
    id: problem-link
    attributes:
      label: Link
      description: "The link of the problem."
      placeholder: "https://leetcode.com/problems/two-sum/"
    validations:
      required: false
